
spring.datasource.url=jdbc:postgresql://ep-twilight-recipe-aecl1rgf-pooler.c-2.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_gtGj5xD9AsSE&sslmode=require&channelBinding=require
spring.datasource.username=thasso
spring.datasource.password=npg_gtGj5xD9AsSE


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret.key=aMinhaChaveSecretaSuperSeguraParaGerarTokensMuitoFortes12345

